import { Link } from 'react-router-dom'
import { ArrowRight, CheckCircle2, Search, ShieldCheck, Sparkles, Zap } from 'lucide-react'
import SEO from '../components/SEO'
import CalculatorCard from '../components/CalculatorCard'
import { calculators, categories } from '../data/calculators'

export default function HomePage(){return <>
  <SEO title="SmartCalc – Fast, Accurate Online Calculators" description="Free calculators for health, finance, math, time, conversions, and everyday life. Clear formulas, careful validation, and instant results."/>
  <section className="hero-section"><div className="eyebrow"><Sparkles size={15}/>Clear answers, without the clutter</div><h1>Everyday calculations,<br/><span>made thoughtfully simple.</span></h1><p>Accurate, easy-to-understand tools for health, money, math, time, conversions, and daily life—right in your browser.</p><div className="hero-actions"><Link className="button primary" to="/calculators"><Search size={18}/>Find a calculator</Link><Link className="button secondary" to="/fitness/bmi">Try BMI calculator<ArrowRight size={18}/></Link></div><div className="trust-row"><span><Zap/>Instant results</span><span><ShieldCheck/>Private by design</span><span><CheckCircle2/>Formula tested</span></div></section>
  <section className="section"><div className="section-heading"><div><p className="kicker">Popular tools</p><h2>Start with a favorite</h2></div><Link to="/calculators">View all <ArrowRight size={16}/></Link></div><div className="tool-grid">{calculators.filter(x=>x.popular).map(x=><CalculatorCard key={x.id} calculator={x}/>)}</div></section>
  <section className="section category-section"><div className="section-heading"><div><p className="kicker">Explore</p><h2>Calculators for every day</h2></div></div><div className="category-grid">{Object.entries(categories).map(([key,c])=>{const Icon=c.icon;return <Link key={key} to={`/calculators?category=${key}`} className="category-card"><Icon/><h3>{c.name}</h3><p>{c.description}</p><span>{calculators.filter(x=>x.category===key).length} tools <ArrowRight size={15}/></span></Link>})}</div></section>
  <section className="section why"><div><p className="kicker">Why SmartCalc</p><h2>Results you can understand</h2><p>Every tool pairs its result with a formula, example, plain-language assumptions, and sensible input checks.</p></div><div className="why-grid"><article><Zap/><h3>Quick by default</h3><p>No account, server round trips, or unnecessary data collection.</p></article><article><CheckCircle2/><h3>Carefully validated</h3><p>Clear errors replace silent bad values, NaN, and misleading output.</p></article><article><ShieldCheck/><h3>Private in your browser</h3><p>Your health and financial inputs stay on your device.</p></article></div></section>
  <section className="section steps"><p className="kicker">How it works</p><h2>From question to answer in three steps</h2><ol><li><b>1</b><span><strong>Choose a tool</strong>Search or browse by category.</span></li><li><b>2</b><span><strong>Enter your values</strong>Helpful limits catch common mistakes.</span></li><li><b>3</b><span><strong>Understand the result</strong>See the result, formula, and assumptions.</span></li></ol></section>
  </>}
