import { Link } from 'react-router-dom'
import { ArrowRight, CheckCircle2, Search, ShieldCheck, Zap } from 'lucide-react'
import SEO from '../components/SEO'
import CalculatorCard from '../components/CalculatorCard'
import { calculators, categories } from '../data/calculators'

export default function HomePage(){return <>
  <SEO title="SmartCalc – Fast, Accurate Online Calculators" description="Free calculators for health, finance, math, time, conversions, and everyday life. Clear formulas, careful validation, and instant results."/>
  <section className="hero-section"><div className="hero-inner"><div className="hero-copy"><h1>Everyday calculations,<br/><span>made simple.</span></h1><p>Accurate, easy-to-use calculators for health, finance, math, time, conversions, and everyday needs.</p><div className="hero-actions"><Link className="button primary" to="/calculators"><Search size={18}/>Browse all calculators</Link><Link className="button secondary" to="/fitness/bmi">Try BMI calculator<ArrowRight size={18}/></Link></div></div><div className="hero-logo" aria-hidden="true"><div className="logo-glow"></div><img src="/smlogo.png" alt=""/></div></div></section>
  <section className="section"><div className="section-heading"><div><p className="kicker">Popular tools</p><h2>Start with the essentials</h2></div><Link to="/calculators">View all <ArrowRight size={16}/></Link></div><div className="tool-grid">{calculators.filter(x=>x.popular).map(x=><CalculatorCard key={x.id} calculator={x}/>)}</div></section>
  <section className="section category-section"><div className="section-heading"><div><p className="kicker">Explore by category</p><h2>Calculators for every need</h2></div></div><div className="category-grid">{Object.entries(categories).map(([key,c])=>{const Icon=c.icon;return <Link key={key} to={`/calculators?category=${key}`} className={`category-card category-${key}`}><span className="category-icon"><Icon/></span><span className="category-copy"><h3>{c.name}</h3><p>{c.description}</p><span className="category-count">{calculators.filter(x=>x.category===key).length} calculators</span></span><ArrowRight className="category-arrow" size={17}/></Link>})}</div></section>
  <section className="section advantages"><div className="section-heading"><div><p className="kicker">Why SmartCalc</p><h2>Built for practical answers</h2></div></div><div className="advantage-grid"><article><span><Zap/></span><h3>Fast calculations</h3><p>Focused tools produce clear results without unnecessary steps.</p></article><article><span><CheckCircle2/></span><h3>Reliable formulas</h3><p>Validated inputs and tested calculation utilities reduce common errors.</p></article><article><span><ShieldCheck/></span><h3>Runs in your browser</h3><p>Calculator values stay on your device and require no account.</p></article></div></section>
  <section className="section steps"><p className="kicker">How it works</p><h2>From input to result in 3 simple steps</h2><ol><li><b>1</b><span><strong>Choose a calculator</strong>Browse or search by category.</span></li><li><b>2</b><span><strong>Enter your values</strong>Clear fields help prevent mistakes.</span></li><li><b>3</b><span><strong>View your result</strong>Review the answer and formula.</span></li></ol></section>
  </>}
